export default function Head() {
  return (
    <>
      <title>PORTFOLIO</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />

      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
