import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Layouts/header/Header";
import { Meteors } from "./components/ui/meteors";



const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} min-h-dvh overflow-hidden max-h-screen flex`}>
        <div className='w-full flex justify-center items-center bg-[url("/bg-image.jpg")] bg-no-repeat bg-center bg-cover overflow-x-hidden' >
          <Meteors number={10} className="ml-32" />
          <Meteors number={5} className="ml-[70%]" />
          <div className="relative backdrop-blur-lg bg-white/10 px-6 w-[95vw] h-[90dvh] border-2 border-slate-50 rounded-2xl flex justify-center sm:w-[90vw] md:w-[80vw] sm:h-[80vh] md:h-[85vh]">
            <Meteors number={5} className="ml-[55%] mt-20" />
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
